Prefix path in 4.0 version
sausin/laravel-ovh pull request #75
Opened 2020-10-05 14:55 UTC by wallacemaxters

2020-10-05 15:01 UTC, iksaku requested changes

2020-10-05 15:01 UTC, iksaku commented on src/OVHSwiftAdapter.php
> +        $expiresAt = $expiration;
You’re breaking the timestamp implementation. Make sure to properly apply time arithmetics, as they’re needed for OVH’s timestamp validation.

2020-10-07 01:47 UTC, sausin commented
Happy to merge when all issues are resolved

2020-10-17 12:07 UTC, sausin commented
Any update on this?

2020-12-17 14:26 UTC, wallacemaxters commented
Hello!

i will fix it

2020-12-25 02:13 UTC, merged

2020-12-25 02:14 UTC, sausin commented
Thanks @wallacemaxters